BLOCKS:
  - "social"
  - "messaging" 
  - "news"
  - "reddit"
  - "feedwrangler"
ADDITIONAL_BLOCKS: 
  - "55.22.44.55"
FIREWALL_RULE_NUMBER: "2"
DISTRACTION_ADDRESS_GROUP_NAME: "Distracting-Stuff"
ROUTER_IP_ADDRESS: "192.168.201.1"
SSH_KEYFILE: "~/.ssh/erl"
SSH_USER: "admin"
FIREWALL_POLICY_NAME: "ETH1_IN"